POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "vídeo node",
  "description": "Esse é o primeiro vídeo",
  "duration": 100
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/3b7b6e19-f82a-4594-a507-5cba98b9540f
Content-Type: application/json

{
  "title": "vídeo 01",
  "description": "Esse é o primeiro vídeo",
  "duration": 100
}

###
DELETE http://localhost:3333/videos/3b7b6e19-f82a-4594-a507-5cba98b9540f